In [2]:
"""
@author : Satwik Ram K

"""
#Importing Libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [3]:
# Importing Datasets
dataset = pd.read_csv('bank-full.csv')

In [4]:
dataset.head(n = 10)

age           job   marital  education default  balance housing loan  \
0   58    management   married   tertiary      no     2143     yes   no   
1   44    technician    single  secondary      no       29     yes   no   
2   33  entrepreneur   married  secondary      no        2     yes  yes   
3   47   blue-collar   married    unknown      no     1506     yes   no   
4   33       unknown    single    unknown      no        1      no   no   
5   35    management   married   tertiary      no      231     yes   no   
6   28    management    single   tertiary      no      447     yes  yes   
7   42  entrepreneur  divorced   tertiary     yes        2     yes   no   
8   58       retired   married    primary      no      121     yes   no   
9   43    technician    single  secondary      no      593     yes   no   

   contact  day month  duration  campaign  pdays  previous poutcome Target  
0  unknown    5   may       261         1     -1         0  unknown     no  
1  unknown    5   may       151         1     -1         0  unknown     no  
2  unknown    5   may        76         1     -1         0  unknown     no  
3  unknown    5   may        92         1     -1         0  unknown     no  
4  unknown    5   may       198         1     -1         0  unknown     no  
5  unknown    5   may       139         1     -1         0  unknown     no  
6  unknown    5   may       217         1     -1         0  unknown     no  
7  unknown    5   may       380         1     -1         0  unknown     no  
8  unknown    5   may        50         1     -1         0  unknown     no  
9  unknown    5   may        55         1     -1         0  unknown     no

In [5]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45211 entries, 0 to 45210
Data columns (total 17 columns):
 #   Column     Non-Null Count  Dtype 
---  ------     --------------  ----- 
 0   age        45211 non-null  int64 
 1   job        45211 non-null  object
 2   marital    45211 non-null  object
 3   education  45211 non-null  object
 4   default    45211 non-null  object
 5   balance    45211 non-null  int64 
 6   housing    45211 non-null  object
 7   loan       45211 non-null  object
 8   contact    45211 non-null  object
 9   day        45211 non-null  int64 
 10  month      45211 non-null  object
 11  duration   45211 non-null  int64 
 12  campaign   45211 non-null  int64 
 13  pdays      45211 non-null  int64 
 14  previous   45211 non-null  int64 
 15  poutcome   45211 non-null  object
 16  Target     45211 non-null  object
dtypes: int64(7), object(10)
memory usage: 5.9+ MB


In [6]:
dataset.describe()

age        balance           day      duration      campaign  \
count  45211.000000   45211.000000  45211.000000  45211.000000  45211.000000   
mean      40.936210    1362.272058     15.806419    258.163080      2.763841   
std       10.618762    3044.765829      8.322476    257.527812      3.098021   
min       18.000000   -8019.000000      1.000000      0.000000      1.000000   
25%       33.000000      72.000000      8.000000    103.000000      1.000000   
50%       39.000000     448.000000     16.000000    180.000000      2.000000   
75%       48.000000    1428.000000     21.000000    319.000000      3.000000   
max       95.000000  102127.000000     31.000000   4918.000000     63.000000   

              pdays      previous  
count  45211.000000  45211.000000  
mean      40.197828      0.580323  
std      100.128746      2.303441  
min       -1.000000      0.000000  
25%       -1.000000      0.000000  
50%       -1.000000      0.000000  
75%       -1.000000      0.000000  
max      871.000000    275.000000

In [7]:
dataset.shape

(45211, 17)

In [8]:
dataset.corr()

age   balance       day  duration  campaign     pdays  previous
age       1.000000  0.097783 -0.009120 -0.004648  0.004760 -0.023758  0.001288
balance   0.097783  1.000000  0.004503  0.021560 -0.014578  0.003435  0.016674
day      -0.009120  0.004503  1.000000 -0.030206  0.162490 -0.093044 -0.051710
duration -0.004648  0.021560 -0.030206  1.000000 -0.084570 -0.001565  0.001203
campaign  0.004760 -0.014578  0.162490 -0.084570  1.000000 -0.088628 -0.032855
pdays    -0.023758  0.003435 -0.093044 -0.001565 -0.088628  1.000000  0.454820
previous  0.001288  0.016674 -0.051710  0.001203 -0.032855  0.454820  1.000000

In [9]:
# Checking for nan values
dataset.isna().sum()

age          0
job          0
marital      0
education    0
default      0
balance      0
housing      0
loan         0
contact      0
day          0
month        0
duration     0
campaign     0
pdays        0
previous     0
poutcome     0
Target       0
dtype: int64

In [10]:
columns = dataset.columns

In [11]:
columns = list(columns)

In [12]:
type(columns)

list

In [13]:
print(len(dataset['Target'].unique()),"\n")

2 



In [14]:
dataset.job.unique()

array(['management', 'technician', 'entrepreneur', 'blue-collar',
       'unknown', 'retired', 'admin.', 'services', 'self-employed',
       'unemployed', 'housemaid', 'student'], dtype=object)

In [15]:
for cols in columns:
    print(cols,"Unique Values:",dataset[cols].unique(),"\n")
    

age Unique Values: [58 44 33 47 35 28 42 43 41 29 53 57 51 45 60 56 32 25 40 39 52 46 36 49
 59 37 50 54 55 48 24 38 31 30 27 34 23 26 61 22 21 20 66 62 83 75 67 70
 65 68 64 69 72 71 19 76 85 63 90 82 73 74 78 80 94 79 77 86 95 81 18 89
 84 87 92 93 88] 

job Unique Values: ['management' 'technician' 'entrepreneur' 'blue-collar' 'unknown'
 'retired' 'admin.' 'services' 'self-employed' 'unemployed' 'housemaid'
 'student'] 

marital Unique Values: ['married' 'single' 'divorced'] 

education Unique Values: ['tertiary' 'secondary' 'unknown' 'primary'] 

default Unique Values: ['no' 'yes'] 

balance Unique Values: [ 2143    29     2 ...  8205 14204 16353] 

housing Unique Values: ['yes' 'no'] 

loan Unique Values: ['no' 'yes'] 

contact Unique Values: ['unknown' 'cellular' 'telephone'] 

day Unique Values: [ 5  6  7  8  9 12 13 14 15 16 19 20 21 23 26 27 28 29 30  2  3  4 11 17
 18 24 25  1 10 22 31] 

month Unique Values: ['may' 'jun' 'jul' 'aug' 'oct' 'nov' 'dec' 'jan' 'feb' 'mar' 'apr' 

In [16]:
for cols in columns:
    print(cols,"Unique Values sums:",len(dataset[cols].unique()),"\n")

age Unique Values sums: 77 

job Unique Values sums: 12 

marital Unique Values sums: 3 

education Unique Values sums: 4 

default Unique Values sums: 2 

balance Unique Values sums: 7168 

housing Unique Values sums: 2 

loan Unique Values sums: 2 

contact Unique Values sums: 3 

day Unique Values sums: 31 

month Unique Values sums: 12 

duration Unique Values sums: 1573 

campaign Unique Values sums: 48 

pdays Unique Values sums: 559 

previous Unique Values sums: 41 

poutcome Unique Values sums: 4 

Target Unique Values sums: 2 



In [17]:
pd.get_dummies(dataset['job'])

admin.  blue-collar  entrepreneur  housemaid  management  retired  \
0           0            0             0          0           1        0   
1           0            0             0          0           0        0   
2           0            0             1          0           0        0   
3           0            1             0          0           0        0   
4           0            0             0          0           0        0   
...       ...          ...           ...        ...         ...      ...   
45206       0            0             0          0           0        0   
45207       0            0             0          0           0        1   
45208       0            0             0          0           0        1   
45209       0            1             0          0           0        0   
45210       0            0             1          0           0        0   

       self-employed  services  student  technician  unemployed  unknown  
0                  0         0        0           0           0        0  
1                  0         0        0           1           0        0  
2                  0         0        0           0           0        0  
3                  0         0        0           0           0        0  
4                  0         0        0           0           0        1  
...              ...       ...      ...         ...         ...      ...  
45206              0         0        0           1           0        0  
45207              0         0        0           0           0        0  
45208              0         0        0           0           0        0  
45209              0         0        0           0           0        0  
45210              0         0        0           0           0        0  

[45211 rows x 12 columns]

In [18]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45211 entries, 0 to 45210
Data columns (total 17 columns):
 #   Column     Non-Null Count  Dtype 
---  ------     --------------  ----- 
 0   age        45211 non-null  int64 
 1   job        45211 non-null  object
 2   marital    45211 non-null  object
 3   education  45211 non-null  object
 4   default    45211 non-null  object
 5   balance    45211 non-null  int64 
 6   housing    45211 non-null  object
 7   loan       45211 non-null  object
 8   contact    45211 non-null  object
 9   day        45211 non-null  int64 
 10  month      45211 non-null  object
 11  duration   45211 non-null  int64 
 12  campaign   45211 non-null  int64 
 13  pdays      45211 non-null  int64 
 14  previous   45211 non-null  int64 
 15  poutcome   45211 non-null  object
 16  Target     45211 non-null  object
dtypes: int64(7), object(10)
memory usage: 5.9+ MB


In [19]:
categories = ['job', 'marital', 'education', 'default', 'housing', 'loan', 'contact', 'month', 'poutcome']
type(categories)

list

In [20]:
dataset.head()

age           job  marital  education default  balance housing loan  \
0   58    management  married   tertiary      no     2143     yes   no   
1   44    technician   single  secondary      no       29     yes   no   
2   33  entrepreneur  married  secondary      no        2     yes  yes   
3   47   blue-collar  married    unknown      no     1506     yes   no   
4   33       unknown   single    unknown      no        1      no   no   

   contact  day month  duration  campaign  pdays  previous poutcome Target  
0  unknown    5   may       261         1     -1         0  unknown     no  
1  unknown    5   may       151         1     -1         0  unknown     no  
2  unknown    5   may        76         1     -1         0  unknown     no  
3  unknown    5   may        92         1     -1         0  unknown     no  
4  unknown    5   may       198         1     -1         0  unknown     no

# Encoding

In [21]:
for cat in categories:
    df = pd.get_dummies(dataset[cat], drop_first = True)
    dataset.drop(cat, axis = 1, inplace = True)
    dataset = pd.concat([dataset, df], axis = 1)

In [22]:
df.head()


other  success  unknown
0      0        0        1
1      0        0        1
2      0        0        1
3      0        0        1
4      0        0        1

In [23]:
print(dataset.shape)
dataset.head()

(45211, 43)


age  balance  day  duration  campaign  pdays  previous Target  blue-collar  \
0   58     2143    5       261         1     -1         0     no            0   
1   44       29    5       151         1     -1         0     no            0   
2   33        2    5        76         1     -1         0     no            0   
3   47     1506    5        92         1     -1         0     no            1   
4   33        1    5       198         1     -1         0     no            0   

   entrepreneur  ...  jul  jun  mar  may  nov  oct  sep  other  success  \
0             0  ...    0    0    0    1    0    0    0      0        0   
1             0  ...    0    0    0    1    0    0    0      0        0   
2             1  ...    0    0    0    1    0    0    0      0        0   
3             0  ...    0    0    0    1    0    0    0      0        0   
4             0  ...    0    0    0    1    0    0    0      0        0   

   unknown  
0        1  
1        1  
2        1  
3        1  
4        1  

[5 rows x 43 columns]

In [29]:
replace_num = {"Target": {"yes": 1 ,"no": 0}}

In [30]:
dataset.replace(replace_num, inplace = True)

# Taking X and Y 

In [31]:
dataset['Target']

0        0
1        0
2        0
3        0
4        0
        ..
45206    1
45207    1
45208    1
45209    0
45210    0
Name: Target, Length: 45211, dtype: int64

In [32]:
x = dataset.drop('Target', axis = 1)

In [33]:
x.shape

(45211, 42)

In [34]:
y = dataset['Target']

In [35]:
y.shape

(45211,)

In [36]:
type(y)

pandas.core.series.Series

In [37]:
y[0]

0

In [39]:
print(y)

0        0
1        0
2        0
3        0
4        0
        ..
45206    1
45207    1
45208    1
45209    0
45210    0
Name: Target, Length: 45211, dtype: int64


# Splitting X and Y 

In [40]:
y.unique()

array([0, 1], dtype=int64)

In [41]:
from sklearn.model_selection import train_test_split


In [42]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 42)

In [43]:
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(36168, 42)
(9043, 42)
(36168,)
(9043,)


#  Normalizing the Data

In [44]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()

In [45]:
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [46]:
x_train

array([[ 0.00651495, -0.16938112, -0.09821817, ..., -0.20779147,
        -0.1860456 ,  0.47280581],
       [ 0.75993671,  0.01784754,  1.70342239, ..., -0.20779147,
        -0.1860456 ,  0.47280581],
       [ 0.10069267,  0.8206814 ,  1.82353176, ..., -0.20779147,
        -0.1860456 ,  0.47280581],
       ...,
       [-0.65272909, -0.01457014, -0.09821817, ..., -0.20779147,
        -0.1860456 ,  0.47280581],
       [-0.74690681, -0.39564332, -1.05909314, ..., -0.20779147,
        -0.1860456 ,  0.47280581],
       [-0.27601821, -0.46378662,  0.62243805, ..., -0.20779147,
        -0.1860456 ,  0.47280581]])

In [47]:
x_test

array([[-0.08766277, -0.25836436,  0.0218912 , ..., -0.20779147,
        -0.1860456 ,  0.47280581],
       [ 0.57158127,  0.75518445, -0.81887439, ..., -0.20779147,
        -0.1860456 ,  0.47280581],
       [-1.50032857, -0.27225765,  0.50232868, ..., -0.20779147,
        -0.1860456 ,  0.47280581],
       ...,
       [ 1.04246987, -0.45022412,  1.22298491, ..., -0.20779147,
        -0.1860456 ,  0.47280581],
       [-0.08766277, -0.19121344,  0.0218912 , ..., -0.20779147,
        -0.1860456 ,  0.47280581],
       [-0.37019593,  0.28049694,  0.50232868, ..., -0.20779147,
        -0.1860456 ,  0.47280581]])

# Applying Support vector Machines

In [48]:
from sklearn.svm import SVC
classifier = SVC(kernel = 'rbf', gamma=5, C=0.001)

from sklearn.linear_model import LogisticRegression
model = LogisticRegression(random_state = 42)

In [49]:
print(type(y_train))
y_train = np.array(y_train)
y_test = np.array(y_test)
print(type(x_train))

<class 'pandas.core.series.Series'>
<class 'numpy.ndarray'>


In [50]:
model.fit(x_train, y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=42, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [51]:
y_pred = model.predict(x_test)

In [52]:
from sklearn.metrics import confusion_matrix, accuracy_score

In [53]:
cm = confusion_matrix(y_test, y_pred)

In [54]:
score = accuracy_score(y_test, y_pred)

In [55]:
cm

array([[7755,  197],
       [ 719,  372]], dtype=int64)

In [56]:
score*100

89.87061815769103

# Lets apply SVM

In [57]:
classifier.fit(x_train, y_train)

SVC(C=0.001, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma=5, kernel='rbf', max_iter=-1,
    probability=False, random_state=None, shrinking=True, tol=0.001,
    verbose=False)

In [58]:
y_pred1 = classifier.predict(x_test)

In [59]:
cm1 = confusion_matrix(y_test, y_pred1)

In [60]:
score1 = accuracy_score(y_test, y_pred1)

In [61]:
cm1

array([[7952,    0],
       [1091,    0]], dtype=int64)

In [62]:
score1*100

87.93541966161672

In [64]:
from sklearn.ensemble import RandomForestClassifier

In [65]:
clf = RandomForestClassifier()

In [66]:
clf.fit(x_train, y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [67]:
y_pred2 = clf.predict(x_test)

In [68]:
cm2 = confusion_matrix(y_test, y_pred2)
score2 = accuracy_score(y_test, y_pred2)

In [69]:
cm2

array([[7733,  219],
       [ 642,  449]], dtype=int64)

In [70]:
score2*100

90.4788233993144